### PR TITLE
Add inCollection

### PR DESCRIPTION
**Pull request by purvakulkarni16**
Added inCollection as an inverse property of CollectionFor.

### CODE REVIEW

**Comment by ufl-taeber** [comment]
Looks good to me. @naomidb, what do you think?

**Comment by naomidb** [comment]
It looks like this is the filling the same role as collectedBy, although I definitely think inCollection is a better name.

**Comment by ufl-taeber** [comment]
I'm not seeing `collectedBy` in the `metabolomics.owl` file although I do see it in the m3c code. Help me out; what am I missing/forgetting?

**Comment by naomidb** [comment]
Perhaps it never got pushed. I like this naming better so I say let's just accept this commit and run with inCollection.

**Comment by naomidb** [comment]
And I've just accidentally hit close so disregard that snafu.

**Pull request merged**
